services:
  webapitestbanre:
    build:
      context: ./ExchangeRateWebApi
      dockerfile: Dockerfile
    image: cas18071998/webapitestbanre:latest
    ports:
      - "5039:5039"
    networks:
      - exchangenet

  consoletestbanre:
    build:
      context: ./ExchangeRateComparator
      dockerfile: Dockerfile
    image: cas18071998/consoletestbanre:latest
    depends_on:
      - webapitestbanre
    environment:
      API_BASE_URL: http://webapitestbanre:5039/api/
    networks:
      - exchangenet
    stdin_open: true
    tty: true  

networks:
  exchangenet:
    driver: bridge